config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'sessions/profile', to: 'sessions#profile'
  get 'gossips/index'
  get 'gossips/new'
  get 'gossips/edit'
  get 'gossips/show'

  resources :gossips
  

  resources :users
  get 'users/show'
  get 'users/index'
  
  resources :cities
  get 'cities/show'

  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  get '/home/:id', to: 'static#home_id'
  get '/home', to: 'static#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user

	has_many :join_table_tag_gossips
	has_many :tags, through: :join_table_tag_gossips

	validates :title, length: { in: 3..15}
	validates :content, presence: true
	#validates :user_id, presence: false
	#validates :user, presence: false

end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord

	belongs_to :gossip
	belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

	belongs_to :recipient, class_name: "User"
	belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :join_table_tag_gossips
	has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips

	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_secure_password

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionsHelper

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@id_city = params[:id]



  end



  def index
  	
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 include ApplicationHelper

  before_action :authenticate_user#, only: [:index]

  def index
  	@gossips = Gossip.all 
  end

  def create
    Gossip.create(title: "#{params[:gossip][:title]}", content: "#{params[:gossip][:content]}", user_id: session[:user_id])
    #Tag.create(title: "#{params[:tag]}")
    #JoinTableTagGossip.create(tag_id: Tag.find_by(title: "#{params[:tag]}").id, gossip_id: Gossip.find_by(title:"#{params[:title]}" ).id)
    

    redirect_to gossips_index_path
  end


  def new
    @gossip = Gossip.new

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(title: "#{params[:gossip][:title]}", content: "#{params[:gossip][:content]}", user_id: session[:user_id], comment:"#{params[:gossip][:comment]}" )
    redirect_to gossips_index_path

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_index_path
  end

  def show
	@id_lien = params[:id]
  @gossip_one = Gossip.find(params[:id])
  @gossip_del = Gossip.find(params[:id]).id
  @id_user = User.find(Gossip.find(params[:id]).user_id).id
  @comment_all = Gossip.where(id: params[:id])
 # @coment = Tag.find(JoinTableTagGossip.find(Gossip.find(params[:id]).id).gossip_id).title
  end

  def add_comment
  #@add comment = Gossip.find(params[:id])
  #@add_comment.comment = "23"
  end


private

def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def profile
	end

	def create
		user = User.find_by(email: params[:email])

	  if user && user.authenticate(params[:password])
	    session[:user_id] = user.id
	    redirect_to sessions_profile_path
	  else
	    flash.now[:danger] = 'Invalid email/password combination'
	    render 'new'
	  end
  	end


	def destroy
		session.delete(:user_id)
		redirect_to new_session_path		
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def team
  end

  def contact
  end

  def home_id
  puts "$" * 60 
  puts params[:id]
  puts "$" * 60

  @user = params[:id]	
  end


  def home
  	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
 @id_user = params[:id]
 @id_city = City.find(User.find(params[:id]).city_id)


  end

  def new
  	@user = User.new
  end

  def create
  	u = User.create(first_name: "#{params[:user][:first_name]}",
  		last_name: "#{params[:user][:last_name]}",
  		description: "#{params[:user][:description]}",
  		email: "#{params[:user][:email]}",
  		age: "#{params[:user][:age]}",
  		city_id: "#{params[:user][:city_id]}", 
  		password: "#{params[:user][:password]}")

  	if u.errors.full_messages == []
  		redirect_to user_path(User.last.id)
  	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def current_user
		User.find_by(id: session[:user_id])
	end

	
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Voici la ville de l'auteur :</p><br>



<div class="card" style="width: 18rem;">
<h5 class="card-body">Ville: <u><%=City.find(@id_city).name%> </u></h5>

</div>

app/views/gossips/edit.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Tu vas pouvoir editer ce Gossip, à toi de jouer !!</p><br>


<%= form_for @gossip do |f| %>
	<div class="form-group">
	<label>Titre du Gossip</label><br>
  <%= f.text_field :title %><br><br>
	<label>Contenu du Gossip</label><br>
  <%= f.text_area :content, size: "60x3" %><br><br>
  <label>Commentaire</label><br>
  <%= f.text_field :comment %><br><br>

  <%= f.submit "Modifier" %>
  </div>
<% end %>

app/views/gossips/index.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<h2>Tu peux cliquer sur ce lien pour créer un nouveau Gossip</h2><br>

<p><a href="<%= new_gossip_path %>">Création Gossip</a></p>
<br><br><hr><br>


<h2>Voici les potins :</h2><br><br>
<div class="div_affichage">
<div class="div_to_hide"> <%= @gossips.each do |gossip|%></div>
<div class="div_main">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Auteur: <u><%=User.find(gossip.user_id).first_name%> <%=User.find(gossip.user_id).last_name%></u></h5>
    <h6 class="card-subtitle mb-2 text-muted">Titre: <%= gossip.title %></h6>
    <p class="card-text">Si tu es curieux, tu peux cliquer sur le lien ci-dessous pour aller découvrir le contenu de ce gossip</p>
    <a href="<%= gossip_path(gossip.id) %>" class="card-link">Lien du Gossip</a>
  </div>
</div>
</div>
<div class="div_to_hide"><% end %></div>

</div>

app/views/gossips/new.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Tu vas pouvoir enregister ton propre Gossip via ce formulaire, à toi de jouer !!</p><br>



  
<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
	<div class="form-group">
	<label>Titre du Gossip</label><br>
  <%= f.text_field :title %><br><br>
	<label>Contenu du Gossip</label><br>
  <%= f.text_area :content, size: "60x3" %><br><br>
  <%= f.submit "Créer" %>
  </div>
<% end %>

app/views/gossips/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Voici ton potin préféré :</p><br>



<div class="card" style="width: 600px;">
  <div class="card-body">
    <h5 class="card1-title">Auteur: <u><%= User.find(Gossip.find(@id_lien).user_id).first_name %> <%= User.find(Gossip.find(@id_lien).user_id).last_name %></u></h5>
    <p>City: <u><%= City.find(User.find(Gossip.find(@id_lien).user_id).city_id).name %></u></p> <hr><br>
    <h6 class="card1-subtitle mb-2 text-muted">Titre: <%= @gossip_one.title %></h6>
    <p class="card1-text">Contenu: <%= @gossip_one.content %></p>
    
    <% if current_user.id == @gossip_one.user_id%>
      <a href="<%= edit_gossip_path(@gossip_one.id) %>" class="card1-link">Editer le Gossip</a>
  	
      <a href="<%= gossip_path(@gossip_one.id) %>" class="card1-link" data-confirm="Êtes-vous certain ?" data-method="DELETE">Supprimer le Gossip</a><br>
    <%end%>

    <a href="<%= user_path(@id_user) %>" class="card1-link">Voir l'Auteur</a>

    <a href="<%= gossips_index_path %>" class="card1-link">Retour Index</a>
  </div>

  <div class="card-body">Commentaire:
  <div class="div_to_hide"><%@comment_all.each do |comment| %></div>
    <ul>
    <li><%= @gossip_one.comment %></li>
    </ul>
    <div class="div_to_hide"><%end%></div>
<% if current_user.id == @gossip_one.user_id%>
    <p><a href="<%= edit_gossip_path(@gossip_one.id) %>" class="card1-link">Ajouter/Editer le Commentaire</a></p>
<%end%>

  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>GossipProjectApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    
    <div class="navbar-nav flex-container">
      <a class="nav-item nav-link active" href="<%= home_path %>">Home ||<span class="sr-only">(current)</span></a>
     <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if current_user %>
     <li> <a class="nav-item nav-link" href="<%= gossips_index_path %>">Index Gossips |</a></li>
      <%end%>
     <li> <a class="nav-item nav-link" href="<%= team_path %>">Team |</a></li>
     <li> <a class="nav-item nav-link" href="<%= contact_path %>">Contact |</a></li>
      </ul>
      </div>

      <% if current_user %>
      
      <div class="dropdown" style="">
  <button class="btn btn-secondary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.first_name %> <%= current_user.last_name %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    
    <a class="dropdown-item" href="<%= sessions_profile_path %>">Profile</a>
    <a class="dropdown-item" href="<%= user_path(current_user.id) %>">  <%= current_user.first_name %> <%= current_user.last_name %></a>
    <p class="dropdown-item"><%= link_to " Se déconnecter ", session_path(session[:user_id]), method: :delete %></p>
  </div>
</div>
      <%else%>
      <button type="button" class="btn btn-dark">
      <a class="nav-item nav-link" href="<%= new_session_path %>">Login</a></button>
      <%end%>

    

  </div>
</nav>
</header>

  <body>
    <div class="div1">
    <%= yield %>
    </div>
  </body>
</html>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/users/new.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Créer ton profil Utilisateur via ce formulaire:</p><br>



  
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
	<div class="form-group">
	<label>Ton prénom</label><br>
  <%= f.text_field :first_name %><br>
  	<label>Ton nom</label><br>
  <%= f.text_field :last_name %><br><br>
  <label>Ton mot de passe</label><br>
  <%= f.text_field :password %><br>
  <label>Confirmes ton mot de passe</label><br>
  <%= f.text_field :password %><br><br>

	<label>Description</label><br>
  <%= f.text_area :description, size: "60x3" %><br><br>
  <label>Ton email</label><br>
  <%= f.text_field :email %><br>
  <label>Ton age</label><br>
  <%= f.text_field :age %><br>
  <label>Ta ville(23)</label><br>
  <%= f.text_field :city_id %><br><br>
  <%= f.submit "Créer" %>
  </div>
<% end %>

<br><br><p>Si après avoir cliqué sur "Créer" vous êtes toujours sur cette page, vous avez fait une erreur dans le formulaire</p>

app/views/users/show.html.erb
<h1>Hello ma ptite salope !</h1><br><br>

<p>Profil auteur :</p><br>


<div class="card" style="width: 600px;">
  <div class="card-body">
    <h5 class="card1-title"> <%=User.find(@id_user).last_name%> <%=User.find(@id_user).first_name%></h5><hr>
    <p class="card1-text">Age: <%=User.find(@id_user).age%> ans<br>E-mail: <%=User.find(@id_user).email%><br>Ville: <%=City.find(User.find(@id_user).city_id).name%><br><br><u>Description:</u> <br><%=User.find(@id_user).description%><br></p>
    <a href="<%= city_path(@id_city.id) %>" class="card1-link">Voir la ville</a>
  </div>
</div>